# Generated by Django 5.1.4 on 2025-01-07 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_nickname',
            field=models.CharField(blank=True, help_text='Please enter your Telegram nickname', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_telegram_nickname', message='Telegram nickname should start with @ and contain only letters, numbers and underscores.                 Length: 5-32 characters.', regex='^@[A-Za-z0-9_]{4,31}$')], verbose_name='Telegram nickname'),
        ),
    ]
