# Generated by Django 5.1.4 on 2025-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_telegram_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Please enter your chat id', max_length=50, null=True, verbose_name='Chat id'),
        ),
    ]
