# Generated by Django 5.1.4 on 2025-01-07 00:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('start_time', models.TimeField(blank=True, help_text='Choose the time when you need to perform the habit', null=True, verbose_name='Start time')),
                ('action', models.CharField(blank=True, help_text='Specify the action of the habit', max_length=100, null=True, verbose_name='The action of habit')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='A sign of a pleasant habit')),
                ('frequency', models.PositiveSmallIntegerField(default=7, help_text='Specify the frequency of habit execution', verbose_name='Frequency of habit execution per week')),
                ('reward', models.CharField(verbose_name='Reward after completing a habit')),
                ('execution_time', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Time to do the habit')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is habit public')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habits.habit', verbose_name='Related habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
